######################################################################
# Automatically generated by qmake (3.0) ?? ??? 1 14:25:21 2016
######################################################################

TEMPLATE = app
TARGET = WebSocketServerQt
INCLUDEPATH += .
QT += core widgets websockets network
QT -= gui

# Input
HEADERS += websocketserverqt.h
SOURCES += main.cpp websocketserverqt.cpp
