######################################################################
# Automatically generated by qmake (3.0) Fri Sep 2 02:41:56 2016
######################################################################

TEMPLATE = app
TARGET = WebSocketClientQt
INCLUDEPATH += . GeneratedFiles
QT += core gui widgets network websockets

# Input
HEADERS += websocketclientqt.h GeneratedFiles/ui_websocketclientqt.h
FORMS += websocketclientqt.ui
SOURCES += main.cpp \
           websocketclientqt.cpp 
